;; This code was automatically generated by the 'metav' library.
(ns keycloak.meta)

(def module-name "keycloak-clojure")
(def path ".")
(def version "1.13.2")
(def tag "v1.13.2")
(def generated-at "2020-11-09T09:43:40Z")
