;; This code was automatically generated by the 'metav' library.
(ns keycloak.meta)

(def module-name "keycloak-clojure")
(def path ".")
(def version "1.14.0")
(def tag "v1.14.0")
(def generated-at "2020-11-06T16:41:23Z")
