;; This code was automatically generated by the 'metav' library.
(ns keycloak.meta)

(def module-name "keycloak-clojure")
(def path ".")
(def version "1.15.0")
(def tag "v1.15.0")
(def generated-at "2021-02-24T14:09:16Z")
