;; This code was automatically generated by the 'metav' library.
(ns keycloak.meta)

(def module-name "keycloak-clojure")
(def path ".")
(def version "1.17.0")
(def tag "v1.17.0")
(def generated-at "2021-06-24T07:43:55Z")
