;; This code was automatically generated by the 'metav' library.
(ns keycloak.meta)

(def module-name "keycloak-clojure")
(def path ".")
(def version "1.31.4")
(def tag "v1.31.4")
(def generated-at "2025-01-27T10:05:19Z")
